name:                lagrange
version:             0.1.0.0
github:              "ratatosk/lagrange"
license:             BSD3
author:              "Pavel Grafov"
maintainer:          "graphov@gmail.com"
copyright:           "2019 Pavel Grafov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ratatosk/lagrange#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lagrange-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lagrange

tests:
  lagrange-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lagrange
